language: php
php:
    - '5.4'
    - '5.5'
    - '5.6'
    - '7.0'
before_script:
    - git clone https://github.com/ezyang/simpletest.git
    - cp test-settings.travis.php test-settings.php
script:
    - php tests/index.php
